# Generated by Django 4.1.7 on 2023-03-20 12:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_category_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('94617ee8-47c3-4230-abc7-e1393f97d901'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('94617ee8-47c3-4230-abc7-e1393f97d901'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('94617ee8-47c3-4230-abc7-e1393f97d901'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='id',
            field=models.UUIDField(default=uuid.UUID('94617ee8-47c3-4230-abc7-e1393f97d901'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('94617ee8-47c3-4230-abc7-e1393f97d901'), primary_key=True, serialize=False),
        ),
    ]
